### PR TITLE
Add new react config

### PR DESCRIPTION
**Pull request by TPRobots**
Pull request opened by github-pullrequestcreator.

### CODE REVIEW

**Comment by thomasthiebaud** [comment]
I love this rule

```
'comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'ignore',
    }
```

it reduce the noise in the commit when you add a new line (the comma is laready here)

**Comment by martinbuberl** [comment]
We had that rule active in the very early days of this project and then disabled the rule again because of popular demand 😄 I guess it comes down to preferences. I'm okay with it changing it back - I personally like it as well - but let's generally not flip flop too much between styles.

**Comment by b-dur** [comment]
I would also prefer having "dangling" commas.

**Comment by madsgodvinjensen** [comment]
Okay, I added the dangling commas. Anything else?

**Pull request merged**
